DASH: Remove unused variables and functions
 * sensors_input_cache.c:59:20:
    error: unused variable 'member'

 * sensors/wrappers/ak896xna_sensors.c:396:23:
    error: unused variable 'd'

 * sensors/wrappers/ak896xna_sensors.c:394:56:
    error: unused parameter 's'

 * sensors/wrappers/ak896xna_sensors.c:388:12:
    error: unused function 'ak896x_form'

 * sensors/ak896xna.c:70:12:
    error: unused function 'ak896x_singleshot'
           ^
 * sensors/ak896xna.c:163:12:
    error: unused function 'ak896x_form'

Change-Id: Ice1ba40e9173c8b7de52acf9f10463fffbf4c223